on:
  - push
  - workflow_dispatch

permissions: write-all

name: 1. DEV Environment Build
jobs:
  build_and_deploy:
    name: Build & Deploy
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-dotnet-service.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
    with:
      DOCKER_IMAGE_NAME: {{ project-name }}-server
      ARTIFACTORY_REPO: {{ org-name }}-{{ solution-name }}-docker-local/applications
